### ISSUE TITLE
Remove the wrapper `ptrMath:` template

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ptr_math#1]
I am opening this issue just to document this for myself.

Ref: https://github.com/nim-lang/Nim/issues/18157#issuecomment-853506938

@timotheecour I realized my misunderstanding with how the `ptrMath` templated worked.

I thought that the inner templates would work only within the `ptrMath:` block. But that's not the case as I now realize. When I use `ptrMath:` once, it just defines those inner templates directly within the scope where I called `ptrMath:`.

What I thought was happening is actually happening only if I used `block:` within the `ptrMath` template definition, but that is not generating the docs as I expected.

I believe there is no reason to have that ptrMath wrapper template. Do you agree? Do you foresee any clashes if those internal `[]`, `[]=` templates get defined in full scope on `import ptr_math`?

### Benefits of removing the wrapper `ptrMath` template

1. Cleaner code -- As now we won't need the `ptrMath:` blocks
2. No need to use `{.used.}` for the inner (which will now be top-level) templates.
3. doc gen works as expected

**Comment by timotheecour** [comment]
> I believe there is no reason to have that ptrMath wrapper template. Do you agree? 

yes; see note in https://github.com/kaushalmodi/ptr_math/pull/2#issuecomment-854056226 regarding `local import` instead

> Do you foresee any clashes if those internal [], []= templates get defined in full scope on import ptr_math?

same as in other cases where use of `foo` defined in multiple imports leads to ambiguity; it's to be expected; local import would also improve these

**Comment by kaushalmodi** [comment]
> where use of foo defined in multiple imports leads to ambiguity

Thanks. From my quick checks, I didn't find any proc that defines `+`, `-` etc where the first arg is a ptr and second is an int... should should be good 🤞  

> local import would also improve these

As that is a language feature, I can see that that cannot happen quickly. If **really** needed, I can introduce an alternative module  that brings back something like the old `ptrMath:` with a `block:` inside.
